### ISSUE TITLE
Emojis not showing and crashing terminal

### ISSUE THREAD

**Issue by NarutoXY** [siduck76/st#14]
https://user-images.githubusercontent.com/79555780/123507557-b923eb00-d687-11eb-9c86-0c74048975a7.mp4

In the video you can see that I am using alacritty and starship prompt. Alacritty renders emojis correctly. But st cannot render the emojis and crashes on my face. I have jet brains mono nerd font also installed and also used default xresoirces but it didnt work

**Comment by siduck76** [comment]
@NarutoXY install ttf-symbola and ttf-emojione

**Comment by NarutoXY** [comment]
I installed both. It was mentioned on Luke Smith St build issues. But it didn't work.

**Comment by NarutoXY** [comment]
Actually it's just Xft problem so I patched it using the libxft-bgra package.

**Comment by siduck76** [comment]
@NarutoXY emojis work for you? on my st

**Comment by siduck76** [comment]
I cant figure out how to use it :(
