### ISSUE TITLE
ligatures patch

### ISSUE THREAD

**Issue by ashincoder** [siduck76/st#15]
hey siduck I was wondering how did u apply ligatures patch. Did u apply ligatures patch before or after boxdraw patch. Then what is the name of the patch. There is two ligatures patch ligatures-alpha and ligatures-boxdraw. Which one did u use

**Comment by siduck76** [comment]
Hi ashin , first apply scrollback , boxdraw and alpha patches  I think I applied all of these order wise 

![image](https://user-images.githubusercontent.com/59060246/124049879-04971a00-da37-11eb-96fa-bd09d8e73b7d.png)

**Comment by siduck76** [comment]
also latest st 0.8.4 had some icon issues for me 

look https://github.com/LukeSmithxyz/st/issues/302

So I just stay with 0.8.2

**Comment by ashincoder** [comment]
thanks man
