### ISSUE TITLE
st crashing with error: RenderBadPicture

### ISSUE THREAD

**Issue by Avimitin** [siduck76/st#16]
`~/.xsession-error` output:

```text
X Error of failed request:  RenderBadPicture (invalid Picture parameter)
  Major opcode of failed request:  140 (RENDER)
  Minor opcode of failed request:  8 (RenderComposite)
  Picture id in failed request: 0xe743
  Serial number of failed request:  61413
  Current serial number in output stream:  61595
```

libxft-bgra-git is installed.

**Comment by Avimitin** [comment]
Dependency are all installed:

```text
$ yay -Qa | ag "(libxft|libx11|harfbuzz|libxext|libxrender|libxinerama)" 
harfbuzz 2.8.2-1 
libx11 1.7.2-1 
libxext 1.3.4-3 
libxft-bgra-git 2.3.3.r112.dcd637d-1 
libxinerama 1.1.4-3 
libxrender 0.9.10-4 
```

And the os I am using is `5.12.15-arch1-1`

**Comment by siduck76** [comment]
install ttf-symbola and ttf-emojione

**Comment by Avimitin** [comment]
I am now using ttf-joypixels as a replacement for ttf-emojione. And I've installed those fonts, but still getting the same error message.

```console
$ yay -Qa | ag "(symbola|joypixels)" 
ttf-joypixels 6.5.0-1 
ttf-symbola 13.00-8 
```

**Comment by siduck76** [comment]
you sure if libXft-bgra is installed?

**Comment by Avimitin** [comment]
> you sure if libXft-bgra is installed?

Yes

```console
$ yay -Qs libxft-bgra
local/libxft-bgra-git 2.3.3.r112.dcd637d-1 (modified)
```

Also, this is not a length error, seems like there is no one met this error
on the simple terminal yet.

**Comment by siduck76** [comment]
this error is common and wont cause anything

![image](https://user-images.githubusercontent.com/59060246/125632058-02f9cb87-1ed5-45a2-b9ac-23662b54ab33.png)

**Comment by Avimitin** [comment]
> 
> 
> this error is common and wont cause anything and doesnt crash either.
> 
> ![image](https://user-images.githubusercontent.com/59060246/125632058-02f9cb87-1ed5-45a2-b9ac-23662b54ab33.png)

But the `X Error of failed request:  RenderBadPicture (invalid Picture parameter)` error will cause crashed.

**Comment by siduck76** [comment]
> > this error is common and wont cause anything and doesnt crash either.
> > ![image](https://user-images.githubusercontent.com/59060246/125632058-02f9cb87-1ed5-45a2-b9ac-23662b54ab33.png)
> 
> But the `X Error of failed request: RenderBadPicture (invalid Picture parameter)` error will cause crashed.

yeah thats odd , only possibilities causing it might be symbola / libxft-bgra not installed :(

**Comment by Avimitin** [comment]
So it looks like this issue is hard to find out the reason and the solution.

**Comment by siduck76** [comment]
> So it looks like this issue is hard to find out the reason and the solution.

remove the git version of bgra and try libXft-bgra

**Comment by Avimitin** [comment]
> 
> 
> > So it looks like this issue is hard to find out the reason and the solution.
> 
> remove the git version of bgra and try libXft-bgra , compile St again and open new st window.

The crash is still happening.

**Comment by siduck76** [comment]
> > > So it looks like this issue is hard to find out the reason and the solution.
> > 
> > 
> > remove the git version of bgra and try libXft-bgra , compile St again and open new st window.
> 
> The crash is still happening.

thats very weird :(

**Comment by Avimitin** [comment]
I've tried not to used tmux all day, and I found that the crash is no more happen. Maybe the st can't draw some character of my tmux. I'll try to reproduce the crash, if nothing happens the reason for the error may be the conflict of tmux configuration with st.

**Comment by siduck76** [comment]
idk much about tmux , share your tmux config so I could test it myself :)

**Comment by Avimitin** [comment]
After 3 days daily use, I can confirm that it may be a tmux render issue. It's not easy to find out which character breaks the st. So I think this issue can be closed down now as it's not so relative. And thanks for your replies.
