### ISSUE TITLE
emoji not rendering properly(no color shown)

### ISSUE THREAD

**Issue by dmatos2012** [siduck76/st#19]
Hi Siduck76,

I am user of your nvim build, and through that saw your dwm and now your `st` fork. I previously had LukeSmith st build, but had always issues with emojis shown. So thanks first of all for the amazing colors and beautifully looking builds.

I am  using your default settings. At the beginning I was having spacing issues, now it renders properly but emojis dont. 
![term2](https://user-images.githubusercontent.com/11776554/128552744-d92479ff-366d-47b6-bff0-2944ac4f4789.png)

OS:
Ubuntu 18.04

`fc-list | grep JetBrains`
```
/home/david/.local/share/fonts/JetBrains Mono Medium Nerd Font Complete Mono.ttf: JetBrainsMono Nerd Font Mono:style=Medium,Regular
/home/david/.local/share/fonts/JetBrains Mono Medium Nerd Font Complete.ttf: JetBrainsMono Nerd Font:style=Medium,Regular
/home/david/.local/share/fonts/JetBrains Mono Regular Nerd Font Complete.ttf: JetBrainsMono Nerd Font:style=Regular
/home/david/.local/share/fonts/JetBrains Mono Regular Nerd Font Complete Mono.ttf: JetBrainsMono Nerd Font Mono:style=Regular
```

`fc-list | grep Iosevka`
```
/home/david/.local/share/fonts/Iosevka Medium Nerd Font Complete Mono.ttf: Iosevka,Iosevka Nerd Font Mono:style=Medium,Regular
/home/david/.local/share/fonts/Iosevka Nerd Font Complete.ttf: Iosevka,Iosevka Nerd Font:style=Regular,Book
/home/david/.local/share/fonts/Iosevka Medium Nerd Font Complete.ttf: Iosevka,Iosevka Nerd Font:style=Medium,Regular/home
```

Also, I have installed the libraries mentioned in your README as well. I also used `xrdb merge xresources` and still no go. Could you help me sort out what the problem could be? 

nb: the emoji does render properly in gnome-terminal or any other terminal not being `st`. I know in ARCH i could use the ttf fonts but yeah I am at a lost now. Thanks!

**Comment by siduck76** [comment]
install libxft-bgra

**Comment by dmatos2012** [comment]
I am on Ubuntu, so thats not possible for me. So I guess without that patch is impossible to get colored emojis on debian/ubuntu?

**Comment by siduck76** [comment]
> I am on Ubuntu, so thats not possible for me. So I guess without that patch is impossible to get colored emojis on debian/ubuntu?
```
git clone https://github.com/uditkarode/libxft-bgra
cd libxft-bgra
sh autogen.sh --sysconfdir=/etc --prefix=/usr --mandir=/usr/share/man
sudo make install
```

**Comment by siduck76** [comment]
this worked for me on void.

**Comment by dmatos2012** [comment]
Yes, I also found that, but key for me was also making sure that when you do `sudo make install`, that it uses the patched one not the one from ubuntu, so that was the key.

So thanks, this has been resolved.

**Comment by UTFeight** [comment]
I was getting this error too!

after opening st emojis work OK.

But using a program like vim did break them


-------------

It turns out that a vim autocmd to remove st padding was breaking emojis.

#54 

Couldn't fix tho
