### ISSUE TITLE
Any luck for windows??

### ISSUE THREAD

**Issue by AzadKshitij** [siduck76/st#21]
I want to use this on windows 
Can I??

**Comment by siduck76** [comment]
check the installation page in our site ( windows section)

**Comment by AzadKshitij** [comment]
Website link??

**Comment by siduck76** [comment]
https://nvchad.netlify.app/

**Comment by siduck76** [comment]
@AzadKshitij oh LOL sorry i thought this was my nvchad repo xD . ST wont work on windows

**Comment by AzadKshitij** [comment]
Lol NVM

**Comment by mohkale** [comment]
st can work on windows. Install wsl and an xserver like [VcXsrv](https://sourceforge.net/projects/vcxsrv/). Then you can run linux GUI apps on windows. Admittedly I wouldn't recommend it for most GUI apps but a fixed width terminal application is perfectly usable, it's what I do :-).
