### ISSUE TITLE
Crashed during make some project like vue-cli

### ISSUE THREAD

**Issue by nenofetch** [siduck76/st#22]
I was facing some issue like i'm make some project using vue-cli (vue create app) the terminal was going force closed/crashed, its also happened on gatsby too. here some preview

https://user-images.githubusercontent.com/22952560/134706188-ae9987e8-3a28-4237-ae99-719c58207e75.mp4

**Comment by siduck76** [comment]
is font-symbola installed?

**Comment by nenofetch** [comment]
Solved, the problem it was from font-symbola not installed before.
Thanks for help
