### ISSUE TITLE
Font Error!!!!

### ISSUE THREAD

**Issue by phanlong2811** [siduck76/st#5]
I have recently set up ST terminal and my ST terminal doesn't display your correct font! How to fix it?
**Note :**  I'm using Ubuntu and I installed JetBrainsMono Nerd Font Mono 

![image](https://user-images.githubusercontent.com/44520002/116582037-242e9b00-a93f-11eb-8d21-f1246625dba4.png)

**Comment by siduck76** [comment]
@phanlong2811 did you try to load xresources? try xrdb merge xresources ( xresources file in repo)

**Comment by phanlong2811** [comment]
> @phanlong2811 did you try to load xresources? try xrdb merge xresources ( xresources file in repo)

I did load it but it didn't work

**Comment by phanlong2811** [comment]
> @phanlong2811 did you try to load xresources? try xrdb merge xresources ( xresources file in repo)

 i loaded it and it worked. Thanks you a lot
 **Btw, can i ask how to make terminal to  default**

**Comment by siduck76** [comment]
not sure about ubuntu! but you can surely check this https://itsfoss.com/change-default-terminal-ubuntu/ :)

**Comment by phanlong2811** [comment]
> not sure about ubuntu! but you can surely check this https://itsfoss.com/change-default-terminal-ubuntu/ :)

It isn't work for me :(

**Comment by siduck76** [comment]
run sudo update-alternatives --config x-terminal-emulator and select st

**Comment by phanlong2811** [comment]
> run sudo update-alternatives --config x-terminal-emulator and select st

no st in here but i'm trying run gsettings set org.gnome.desktop.default-applications.terminal exec /usr/local/bin/st and it work for me! Thank you a lot <3

**Comment by siduck76** [comment]
you're welcome! close the issue if ST's working fine  and feel free to make more issues! I'll help out >:).
