### ISSUE TITLE
How to autoreload xresources when I log in Ubuntu

### ISSUE THREAD

**Issue by phanlong2811** [siduck76/st#6]
When I log in, some settings change default and I must reload xresources when i turn on ST terminal. How to solve that ???
P/s : actually I don't know what xresources is so I don't know solve that :( Do you have a discord sever? Plz send me, I need your help :<
![image](https://user-images.githubusercontent.com/44520002/116607288-002d8280-a95c-11eb-8891-10993f41e716.png)

**Comment by phanlong2811** [comment]
> When I log in, some settings change default and I must reload xresources when i turn on ST terminal. How to solve that ???
> P/s : actually I don't know what xresources is so I don't know solve that :( Do you have a discord room, plz send me, I need your help :(
> ![image](https://user-images.githubusercontent.com/44520002/116607288-002d8280-a95c-11eb-8891-10993f41e716.png)

**Comment by siduck76** [comment]
@phanlong2811 siduck76#5226 is my discord account. To reload xresources , you need to add xrdb merge xresources ( xresources from repo ) , at your autostart options . move the xresources file in your home folder so it gets easy . Idk much gnome!
