### ISSUE TITLE
Building under debian

### ISSUE THREAD

**Issue by m-fonseca** [siduck76/st#7]
Hello,

FYI, You will need the following dependencies to build under Debian (Ubuntu is probably similar):

    apt install build-essential libxft-dev libharfbuzz-dev

**Comment by siduck76** [comment]
@m-fonseca  It builds with those dependencies right?

**Comment by siduck76** [comment]
> Hello,
> 
> FYI, You will need the following dependencies to build under Debian (Ubuntu is probably similar):
> 
> ```
> apt install build-essential libxft-dev libharfbuzz-dev
> ```

I have added this in the readme. Thanks for this!
