### ISSUE TITLE
Wrong Font

### ISSUE THREAD

**Issue by zynsdev** [siduck76/st#9]
Because you delete the repo [matfonts](https://github.com/siduck76/matfonts), I can't install rigth fonts. 

![image](https://user-images.githubusercontent.com/68643009/119235288-f1517e80-bb5b-11eb-82af-82e2c61d001d.png)

Please help me!

**Comment by siduck76** [comment]
@zynsdev install these fonts :

 JetbrainsMono Nerd Font + material design icon fonts

**Comment by zynsdev** [comment]
> @zynsdev install these fonts :
> 
> JetbrainsMono Nerd Font + material design icon fonts
> 
> if you're on arch then its easy with aur or download them manually here :
> 
> https://www.nerdfonts.com/font-downloads
> https://materialdesignicons.com/

Thanks you very much

**Comment by siduck76** [comment]
Since this issue is solved , I'll close it . re-open it if you want to!
